/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:386e5d7b-65ef-4734-8cb5-b77e3bc9ff89",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_rPCz9Ahhl",
    "aws_user_pools_web_client_id": "tjeodeq03uscqjofdkulg5jtv",
    "oauth": {
        "domain": "loginscreen4cf3c84b-4cf3c84b-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
